### ISSUE TITLE
GetTextRange wide character inconsistency

### ISSUE THREAD

**Issue by otykier** [desjarlais/Scintilla.NET#65]
**Describe the bug**
The `length` parameter of the `GetTextRange` method is not consistent with the `TextLength` property and other length/positional properties of Scintilla.NET.

**To Reproduce**
```csharp
var text = "😁😁😁";
Assert.AreEqual(6, text.Length); // Succeeds, because each 😁 is 2 characters wide
Assert.AreEqual("😁", text.Substring(0, 2)); // Succeeds

scintilla1.Text = text;
Assert.AreEqual(6, scintilla1.TextLength); // Succeeds
Assert.AreEqual(6, scintilla1.Lines[0].EndPosition); // Succeeds
Assert.AreEqual("😁", scintilla1.GetTextRange(0, 2)); // Fails, as GetTextRange returns "😁😁"
```

**Expected behavior**
`GetTextRange` should have consistent behavior with the other length/position properties and methods of Scintilla.NET. The inconsistency is illustrated above. Alternatively, there should be another method or an optional parameter that lets us specify how wide characters should be handled.

**Comment by VPKSoft** [comment]
Hi,
Thanks for reporting this and 👍for the sample code.

**Comment by desjarlais** [comment]
@otykier do you still reproduce this behavior?  My initial test of the sample provided was returning true for GetTextRange.

**Comment by otykier** [comment]
Unfortunately, the issue persists. Just tested now with 5.3.3.6. Take a look at the attached sample project.

In these examples, we use the `scintilla.SelectionStart` and `scintilla.SelectionEnd` property to determine the range of the selection.

When selecting a character before the wide char (emoji), everything is good, and `string.Substring`, `scintilla.GetTextRange` and `scintilla.SelectedText` returns the same result:

<img width="302" alt="image" src="https://github.com/desjarlais/Scintilla.NET/assets/8976200/64496508-1600-478b-bd41-aa5adb288d61">

Selecting the wide char, `scintilla.GetTextRange` now returns a different string than `string.Substring` or `scintilla.SelectedText`:

<img width="301" alt="image" src="https://github.com/desjarlais/Scintilla.NET/assets/8976200/3d0b3fa9-b43f-4305-b688-864f6ef4643f">

And finally, if we go beyond the wide char, we get an exception if we try to use `scintilla.GetTextRange`:

<img width="380" alt="image" src="https://github.com/desjarlais/Scintilla.NET/assets/8976200/463a4839-280a-4dad-981b-39c2f51c0858">

I'm not sure if this is an issue in the native Scintilla control, or in the Scintilla.NET wrapper. But the main issue, as far as I can tell, is that there is inconsistency between how wide characters are counted. In a .NET string, they should be counted as 2 characters, and that is also what `scintilla.SelectionStart` and `scintilla.SelectionEnd` does (as seen from the screenshots above). But other methods, such as `scintilla.GetTextRange` seem to only count wide characters as a single character.

[WinFormsApp1.zip](https://github.com/desjarlais/Scintilla.NET/files/13610819/WinFormsApp1.zip)

**Comment by desjarlais** [comment]
That does repro, I'll see what I can find out.  Thank you for the report!

**Comment by desjarlais** [comment]
There are two things to discuss here, because your examples are different.

1. Your first example is:

var text = "😁😁😁";
scintilla1.Text = text;
Assert.AreEqual("😁", scintilla1.GetTextRange(0, 2)); // Fails, as GetTextRange returns "😁😁"

In my opinion, that should fail.  Keep in mind, position and length args for GetTextRange are character based as far as I can tell:

/// <param name="position">The zero-based starting character position of the range to get.</param>
/// <param name="length">The number of characters to get.</param>

So you are asking GetTextRange to return 2 characters starting from the beginning of the line.  Which it does and two emoji's are not equal to 1 emoji.  

2. Your second example does seem to show a bug that appears to be coming from CharToBytePosition, which was getting too many characters for the end byte position in GetTextRange.  Which seems to be why the extra characters and exception were happening in your sample.  

I'm testing a fix that sets the code page when the line has multibyte characters.  It seems to work but I want to play with it a little bit more since this function has 63 references and as far as I can tell hasn't been touched since 2015.

**Comment by otykier** [comment]
> In my opinion, that should fail. Keep in mind, position and length args for GetTextRange are character based as far as I can tell:
>
> name="position">The zero-based starting character position of the range to get.
> name="length">The number of characters to get.
> 
> So you are asking GetTextRange to return 2 characters starting from the beginning of the line. Which it does and two emoji's are not equal to 1 emoji.

The issue here is the inconsistency between methods like `GetTextRange` and `TextLength`. Since `TextLength` returns 6 for the string `"😁😁😁"`, one would assume that calling `GetTextRange(0, 6)` would produce a valid result, but it doesn't.

But thanks a lot for looking into this. I realize this is a tough not to crack, and I have no idea if the issue originates in the native Scintilla codebase, or in the .NET wrapper.

**Comment by desjarlais** [comment]
Fair enough, it is inconsistent.  So using Selection based ranges is more of the user scenario you are trying to solve and not handing the function a number?

**Comment by desjarlais** [comment]
I'm leaning towards not changing anything here because it seems like it is intentional to work this way.  It is not consistent per se, but I'm seeing these as two different tools for two different types of jobs.

1. If you want to use a selection based range from the control, then use the SelectedText example similar to what you provided in your repro sample.  
2. If you want to get a literal number of visible characters outside of the selection, then GetTextRange seems like it will be the better option. 

What is the scenario you are trying to solve for with this sample repro?

**Comment by desjarlais** [comment]
try version 5.3.3.11 and see if GetTextRange works the way you are expecting

**Comment by desjarlais** [comment]
This fix in #111 introduces a new fix for this issue...adding a new function "GetWideTextRange" instead of using "GetTextRange" if you want to include wide characters in a get text style function.

**Comment by otykier** [comment]
[heart]         Daniel Otykier reacted to your message:
________________________________

**Comment by otykier** [comment]
That’s great, thanks a lot!
